CREATE TABLE cat_merged (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INT NOT NULL,
    total_cats INT NULL,
    average_age DOUBLE PRECISION NULL
);

INSERT INTO cat_merged (id, name, age, total_cats, average_age)
SELECT c.id, c.name, c.age, s.total_cats, s.average_age
FROM cats c CROSS JOIN cat_stats s;

SELECT setval(
    pg_get_serial_sequence('cat_merged', 'id'),
    (SELECT MAX(id) FROM cat_merged)
);

DROP TABLE cat_stats;
DROP TABLE cats;