spring.application.name=springDB-hw

# Primary DataSource Configuration
spring.datasource.primary.jdbc-url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.primary.username=admin
spring.datasource.primary.password=admin
spring.datasource.primary.driver-class-name=org.postgresql.Driver

spring.datasource.primary.maximum-pool-size=20
spring.datasource.primary.connection-timeout=1000

# Replica DataSource Configuration
spring.datasource.replica.jdbc-url=jdbc:postgresql://localhost:5433/mydb
spring.datasource.replica.username=admin
spring.datasource.replica.password=admin
spring.datasource.replica.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update